---
apiVersion: v1
kind: Service
metadata:
  name: monnginx-service
spec:
  selector:
    app: monpods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32200
  type: NodePort  # Exposer à l'extérieur du cluster

